### ISSUE TITLE
Make available on PyPi

### ISSUE THREAD

**Issue by dyve** [theatlantic/django-chosen#10]
Could you make this available on PyPi http://pypi.python.org/?

**Comment by domenkozar** [comment]
I have uploaded it to pypi, if you want admin rights, tell me your username.

http://pypi.python.org/pypi/django-chosen/0.1

Command used:

python setup.py egg_info -RDb "" sdist register upload

**Comment by fdintino** [comment]
We've set up username "theatlantic". If you could grant admin rights we would appreciate it.

Thanks.

**Comment by domenkozar** [comment]
Done!
