### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by houmie** [theatlantic/django-chosen#18]
Hello,

I have installed django-chosen extension by PIP successfully,

$ pip install -e git+git://github.com/theatlantic/django-chosen.git#egg=django-chosen

however when I try to import it in my forms.py:

"import from chosen import forms as chosenforms"

it throws an error. It doesn't see it. Any idea why? The documentation doesn't mention any other setup steps. So I am really stuck on this.

Many thanks for your advice,
Houman

P.S. this is how I installed it:

`$ sudo pip install -e git+git://github.com/theatlantic/django-chosen.git#egg=django-chosen

Obtaining django-chosen from git+git://github.com/theatlantic/django-chosen.git#egg=django-chosen
  Cloning git://github.com/theatlantic/django-chosen.git to /src/django-chosen
  Running setup.py egg_info for package django-chosen

```
warning: manifest_maker: MANIFEST.in, line 5: unknown action 'reverse-include'
```

Installing collected packages: django-chosen
  Running setup.py develop for django-chosen
    Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
    /usr/bin/python -E -c pass
    TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files

```
warning: manifest_maker: MANIFEST.in, line 5: unknown action 'reverse-include'

Creating /usr/local/lib/python2.7/dist-packages/django-chosen.egg-link (link to .)
Adding django-chosen 0.1 to easy-install.pth file

Installed /src/django-chosen
```

Successfully installed django-chosen
Cleaning up...`

**Comment by jsam** [comment]
launch python shell inside your django app like this.

python manage.py shell

then try out this:

from chosen import forms as chosenforms 

(and not "import from chosen import forms as chosenforms" like you wrote cause its syntax error)
I am fiddling with this app right now and this works for me.

**Comment by houmie** [comment]
Sam,

I think the problem is the way the documentation suggests to install it.

 $ pip install -e git+git://github.com/theatlantic/django-chosen.git#egg=django-chosen

I uninstalled it and reinstalled this way three times and it still failed.

Now I tried to install it like this:

$ pip install django-chosen

Now it works right away.  I am no expert in pip and what is going on behind the scenes, but maybe its better to update the documentation to rather to this.  

Thanks for your help on this,

**Comment by fdintino** [comment]
The issue with the installation instructions is that the repository should be quoted when passed to pip install, e.g.

```
pip install -e "git+git://github.com/theatlantic/django-chosen.git#egg=django-chosen"
```

I've updated the README to reflect this.
