### ISSUE TITLE
`overlay` option doesn't work in admin

### ISSUE THREAD

**Issue by ivirabyan** [theatlantic/django-chosen#19]
Since django-admin uses an old version of jQuery (1.4.2), and django-chosen uses jQuery included in django-admin, `el.data('placeholder')` returns `null`

One approach would be to use `jQuery` instead of `django.jQuery` if provided.
Then I could include my own version of jQuery into the model admin.

**Comment by fdintino** [comment]
There is a currently open ticket on the chosen javascript github for this problem ([Issue #347](https://github.com/harvesthq/chosen/issues/347)). I would recommend lobbying for my patch to fix [Issue #893: Allow Chosen to be initialized with a specific version of jQuery](https://github.com/harvesthq/chosen/issues/893#issuecomment-10671226).

**Comment by fdintino** [comment]
Once [chosen pull request #1394](https://github.com/harvesthq/chosen/pull/1394) is merged and it has been subsequently updated in this repository, I'll be able to close this issue. That pull request removes the dependency on jQuery.

**Comment by radzhome** [comment]
this plugin doesn't work at all for me in admin, just loads up a disabled select when i use it. How can I get {{ form.media }} into admin?
