### ISSUE TITLE
static files missing

### ISSUE THREAD

**Issue by domguard** [theatlantic/django-chosen#4]
very strange. I installed django-chosen on my Mac and onto my Linux VM using pip install (with or without -e option)
On the mac, I have the static folder, but not on Linux.
Perhaps you're missing a MANIFEST.IN file to specify .css and .js files ?

**Comment by ortsed** [comment]
Just added a Manifest.in file for this purpose.

**Comment by fdintino** [comment]
I believe this is fixed now with the inclusion of the Manifest.in file.
